definitions:
  timetracking.User:
    properties:
      address:
        description: адрес
        type: string
      name:
        description: имя
        type: string
      patronymic:
        description: отчество
        type: string
      surname:
        description: фамилия
        type: string
    type: object
info:
  contact: {}
paths:
  /begin-task-for-user:
    post:
      consumes:
      - application/json
      description: Begin task for user
      parameters:
      - description: Passport number
        in: body
        name: pasportNumber
        required: true
        schema:
          type: string
      - description: Task ID
        in: body
        name: taskId
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Неверные параметры запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Begin task for user
      tags:
      - Time Tracking
  /calculate-cost-by-user:
    get:
      consumes:
      - application/json
      description: Возвращает затраты времени на задачи по идентификатору пользователя
      parameters:
      - description: Серия паспорта
        in: query
        name: pasportSeries
        required: true
        type: string
      - description: Номер паспорта
        in: query
        name: pasportNumber
        required: true
        type: string
      - description: Начало периода (в формате ISO 8601)
        in: query
        name: periodFrom
        required: true
        type: string
      - description: Окончание периода (в формате ISO 8601)
        in: query
        name: periodTo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список счетов (costs)
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверные параметры запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Затраты времени на задачи
      tags:
      - Time Tracking
  /end-task-for-user:
    post:
      description: Finish tracking time for a specific task
      parameters:
      - description: Passport number
        in: body
        name: pasportNumber
        required: true
        schema:
          type: string
      - description: Task ID
        in: body
        name: taskId
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Неверные параметры запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Finish task time tracking
  /info:
    get:
      consumes:
      - application/json
      description: Get user data by passport series and number
      parameters:
      - description: Passport series
        in: query
        name: pasportSeries
        required: true
        type: string
      - description: Passport number
        in: query
        name: pasportNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/timetracking.User'
        "400":
          description: Неверные параметры запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Get user data
      tags:
      - User
  /users:
    delete:
      consumes:
      - application/json
      description: Delete user by passport series and number
      parameters:
      - description: Passport series
        in: query
        name: pasportSeries
        required: true
        type: string
      - description: Passport number
        in: query
        name: pasportNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Неверные параметры запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Delete user
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Get users data by filter and pagination
      parameters:
      - description: Filter
        in: query
        name: filter
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/timetracking.User'
            type: array
        "400":
          description: Неверные параметры запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Get users data by filter and pagination
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create user with passport data
      parameters:
      - description: User data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/timetracking.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: int32
        "400":
          description: Неверные параметры запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Create user
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update user data by passport series and number
      parameters:
      - description: Passport series
        in: query
        name: pasportSeries
        required: true
        type: string
      - description: Passport number
        in: query
        name: pasportNumber
        required: true
        type: string
      - description: User data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/timetracking.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Неверные параметры запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Update user data
      tags:
      - User
swagger: "2.0"
